package compliance

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"strings"
)

// exportJSON writes the full report as JSON.
func exportJSON(r *Report, w io.Writer) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	if err := enc.Encode(r); err != nil {
		return fmt.Errorf("encoding JSON: %w", err)
	}
	return nil
}

// exportCSV flattens all events from every section into CSV rows.
func exportCSV(r *Report, w io.Writer) error {
	cw := csv.NewWriter(w)
	defer cw.Flush()

	header := []string{
		"section",
		"timestamp",
		"action",
		"resource",
		"resource_id",
		"category",
		"outcome",
		"severity",
		"user_id",
		"ip",
		"reason",
	}
	if err := cw.Write(header); err != nil {
		return fmt.Errorf("writing CSV header: %w", err)
	}

	for _, s := range r.Sections {
		for _, ev := range s.Events {
			row := []string{
				s.Title,
				ev.Timestamp.UTC().Format("2006-01-02T15:04:05Z"),
				ev.Action,
				ev.Resource,
				ev.ResourceID,
				ev.Category,
				ev.Outcome,
				ev.Severity,
				ev.UserID,
				ev.IP,
				ev.Reason,
			}
			if err := cw.Write(row); err != nil {
				return fmt.Errorf("writing CSV row: %w", err)
			}
		}
	}

	cw.Flush()
	return cw.Error()
}

// exportMarkdown renders the report as a Markdown document.
func exportMarkdown(r *Report, w io.Writer) error {
	var b strings.Builder

	b.WriteString("# ")
	b.WriteString(r.Title)
	b.WriteString("\n\n")

	b.WriteString("**Type:** ")
	b.WriteString(r.Type)
	b.WriteString("  \n")

	b.WriteString("**Period:** ")
	b.WriteString(r.Period.From.UTC().Format("2006-01-02"))
	b.WriteString(" to ")
	b.WriteString(r.Period.To.UTC().Format("2006-01-02"))
	b.WriteString("  \n")

	b.WriteString("**App ID:** ")
	b.WriteString(r.AppID)
	b.WriteString("  \n")

	if r.TenantID != "" {
		b.WriteString("**Tenant ID:** ")
		b.WriteString(r.TenantID)
		b.WriteString("  \n")
	}

	b.WriteString("**Generated By:** ")
	b.WriteString(r.GeneratedBy)
	b.WriteString("  \n\n")

	if r.Stats != nil {
		b.WriteString("## Summary\n\n")
		b.WriteString("| Metric | Count |\n")
		b.WriteString("| --- | --- |\n")
		fmt.Fprintf(&b, "| Total Events | %d |\n", r.Stats.TotalEvents)
		fmt.Fprintf(&b, "| Critical Events | %d |\n", r.Stats.CriticalEvents)
		fmt.Fprintf(&b, "| Failed Events | %d |\n", r.Stats.FailedEvents)
		fmt.Fprintf(&b, "| Denied Events | %d |\n", r.Stats.DeniedEvents)
		b.WriteString("\n")
	}

	for _, s := range r.Sections {
		b.WriteString("## ")
		b.WriteString(s.Title)
		b.WriteString("\n\n")

		if s.Notes != "" {
			b.WriteString(s.Notes)
			b.WriteString("\n\n")
		}

		if len(s.Events) == 0 {
			b.WriteString("_No events in this section._\n\n")
			continue
		}

		b.WriteString("| Timestamp | Action | Resource | Category | Outcome | Severity |\n")
		b.WriteString("| --- | --- | --- | --- | --- | --- |\n")

		for _, ev := range s.Events {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %s | %s |\n",
				ev.Timestamp.UTC().Format("2006-01-02 15:04:05"),
				ev.Action,
				ev.Resource,
				ev.Category,
				ev.Outcome,
				ev.Severity,
			)
		}

		b.WriteString("\n")
	}

	_, err := io.WriteString(w, b.String())
	if err != nil {
		return fmt.Errorf("writing markdown: %w", err)
	}
	return nil
}

// htmlTemplate is the HTML template for compliance report rendering.
var htmlTemplate = template.Must(template.New("report").Parse(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{.Title}}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; margin: 2rem; color: #333; line-height: 1.6; }
  h1 { border-bottom: 2px solid #2563eb; padding-bottom: 0.5rem; color: #1e40af; }
  h2 { color: #1e40af; margin-top: 2rem; }
  .meta { background: #f0f4ff; padding: 1rem; border-radius: 8px; margin-bottom: 2rem; }
  .meta p { margin: 0.25rem 0; }
  .stats { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }
  .stat-card { background: #fff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 1rem 1.5rem; min-width: 150px; }
  .stat-card .label { font-size: 0.85rem; color: #64748b; }
  .stat-card .value { font-size: 1.5rem; font-weight: bold; color: #1e293b; }
  .stat-card.critical .value { color: #dc2626; }
  .stat-card.failed .value { color: #ea580c; }
  .stat-card.denied .value { color: #9333ea; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 1.5rem; font-size: 0.9rem; }
  th { background: #f1f5f9; text-align: left; padding: 0.5rem 0.75rem; border-bottom: 2px solid #cbd5e1; }
  td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #e2e8f0; }
  tr:hover td { background: #f8fafc; }
  .notes { color: #64748b; font-style: italic; margin-bottom: 1rem; }
  .empty { color: #94a3b8; font-style: italic; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>{{.Title}}</h1>
<div class="meta">
  <p><strong>Type:</strong> {{.Type}}</p>
  <p><strong>Period:</strong> {{.Period.From.UTC.Format "2006-01-02"}} to {{.Period.To.UTC.Format "2006-01-02"}}</p>
  <p><strong>App ID:</strong> {{.AppID}}</p>
  {{if .TenantID}}<p><strong>Tenant ID:</strong> {{.TenantID}}</p>{{end}}
  <p><strong>Generated By:</strong> {{.GeneratedBy}}</p>
</div>

{{if .Stats}}
<div class="stats">
  <div class="stat-card">
    <div class="label">Total Events</div>
    <div class="value">{{.Stats.TotalEvents}}</div>
  </div>
  <div class="stat-card critical">
    <div class="label">Critical Events</div>
    <div class="value">{{.Stats.CriticalEvents}}</div>
  </div>
  <div class="stat-card failed">
    <div class="label">Failed Events</div>
    <div class="value">{{.Stats.FailedEvents}}</div>
  </div>
  <div class="stat-card denied">
    <div class="label">Denied Events</div>
    <div class="value">{{.Stats.DeniedEvents}}</div>
  </div>
</div>
{{end}}

{{range .Sections}}
<h2>{{.Title}}</h2>
{{if .Notes}}<p class="notes">{{.Notes}}</p>{{end}}
{{if .Events}}
<table>
<thead>
<tr><th>Timestamp</th><th>Action</th><th>Resource</th><th>Category</th><th>Outcome</th><th>Severity</th></tr>
</thead>
<tbody>
{{range .Events}}
<tr>
  <td>{{.Timestamp.UTC.Format "2006-01-02 15:04:05"}}</td>
  <td>{{.Action}}</td>
  <td>{{.Resource}}</td>
  <td>{{.Category}}</td>
  <td>{{.Outcome}}</td>
  <td>{{.Severity}}</td>
</tr>
{{end}}
</tbody>
</table>
{{else}}
<p class="empty">No events in this section.</p>
{{end}}
{{end}}

<footer>
  <p>Generated by Chronicle Compliance Engine</p>
</footer>
</body>
</html>
`))

// exportHTML renders the report using an HTML template.
func exportHTML(r *Report, w io.Writer) error {
	if err := htmlTemplate.Execute(w, r); err != nil {
		return fmt.Errorf("rendering HTML: %w", err)
	}
	return nil
}
